# core/rule_generator.py
import os
import subprocess
import re
from config import Config

def generate_rules(sample_dir, output_dir=None):
    """Generate YARA rules using yarGen or a simple string extraction."""
    if output_dir is None:
        output_dir = os.path.join(Config.RULES_DIR, 'auto_generated')
    os.makedirs(output_dir, exist_ok=True)

    # Try yarGen if available
    try:
        subprocess.run(['yarGen', '-o', output_dir, sample_dir], check=True, timeout=300)
        print(f"✅ YARA rules generated by yarGen in {output_dir}")
        return output_dir
    except FileNotFoundError:
        print("⚠️ yarGen not found. Using fallback string extraction.")
    except subprocess.TimeoutExpired:
        print("⚠️ yarGen timed out. Using fallback.")

    # Fallback: simple string extraction from sample files
    all_strings = []
    for f in os.listdir(sample_dir):
        path = os.path.join(sample_dir, f)
        try:
            with open(path, 'rb') as fd:
                data = fd.read()
                # Extract printable strings longer than 6 chars
                strings = re.findall(b'[ -~]{6,}', data)
                all_strings.extend([s.decode('utf-8', errors='ignore') for s in strings])
        except:
            continue

    # Deduplicate and sort by frequency
    from collections import Counter
    freq = Counter(all_strings)
    top_strings = [s for s, c in freq.most_common(20) if len(s) > 8]

    # Write a YARA rule
    rule_path = os.path.join(output_dir, 'auto_generated.yar')
    with open(rule_path, 'w') as f:
        f.write('rule AutoGenerated {\n')
        f.write('    meta:\n')
        f.write('        description = "Auto-generated rule from sample strings"\n')
        f.write('    strings:\n')
        for i, s in enumerate(top_strings):
            f.write(f'        $s{i} = "{s}"\n')
        f.write('    condition:\n')
        if top_strings:
            f.write('        2 of them\n')
        else:
            f.write('        false\n')
        f.write('}\n')

    print(f"✅ Fallback YARA rule generated: {rule_path}")
    return output_dir